---

version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Rome
    allow:
      - dependency-type: all
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: '05:00'
      timezone: Europe/Rome
